legacy workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,6 +7,11 @@ on:
         description: "Version of BOS CLI to use for deploy (e.g. 0.3.0)"
         type: string
         default: "0.3.6"
+      bw-legacy:
+        required: false
+        description: "Flag to use legacy BOS Workspace deploy (e.g. 0.0.1-alpha.7)"
+        type: boolean
+        default : true
       deploy-env:
         required: false
         description: "Environment to deploy component code to (e.g. mainnet, testnet)"
@@ -70,27 +75,40 @@ jobs:
         with:
           node-version: "18"
 
+      - name: Check bw-legacy flag
+        run: |
+          if [ "${{ inputs.bw-legacy }}" = "true" ]; then
+            export BW_VERSION="version/0.0.1-alpha.7"
+          else
+            export BW_VERSION="main"
+          fi
+
       - name: Install bos-workspace globally
         run: |
-          npm install -g git+https://github.com/NEARBuilders/bos-workspace.git#1.0.0.wip
+          npm install -g git+https://github.com/NEARBuilders/bos-workspace.git#${BW_VERSION}
 
       - name: Check for bos.workspace.json or bos.config.json
         run: |
           cd "$WORKING_DIRECTORY"
-          if [ -f "bos.workspace.json" ]; then
-            echo "Found bos.workspace.json"
-            BUILD_COMMAND="bos-workspace ws build"
-            BUILD_PATH="$WORKING_DIRECTORY/build/apps/$BOS_APP_NAME"
-          elif [ -f "bos.config.json" ]; then
-            echo "Found bos.config.json"
+          if [ "${{ inputs.bw-legacy }}" = "true" ]; then
             BUILD_COMMAND="bos-workspace build"
             BUILD_PATH="$WORKING_DIRECTORY/build/$BOS_APP_NAME"
           else
-            echo "Neither bos.workspace.json nor bos.config.json found, aborting"
-            exit 1
+            if [ -f "bos.workspace.json" ]; then
+              echo "Found bos.workspace.json"
+              BUILD_COMMAND="bos-workspace ws build"
+              BUILD_PATH="$WORKING_DIRECTORY/dist/apps/$BOS_APP_NAME"
+            elif [ -f "bos.config.json" ]; then
+              echo "Found bos.config.json"
+              BUILD_COMMAND="bos-workspace build"
+              BUILD_PATH="$WORKING_DIRECTORY/dist/$BOS_APP_NAME"
+            else
+              echo "Neither bos.workspace.json nor bos.config.json found, aborting"
+              exit 1
+            fi
           fi
 
-      - name: Build the workspaces
+      - name: Build the workspace
         run: |
           $BUILD_COMMAND
 
